#!/usr/bin/env -S uv run python
"""
commands/group_invite [-p tdata/--path-to-tdata=tdata] [-s .session/--session=.session] @username/id @groupname/id

Invites a user into the given group/channel.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse
import asyncio

from libs.cli import add_client_arguments, client_kwargs, emit
from methods.group_invite import invite


async def main() -> None:
    parser = argparse.ArgumentParser()
    add_client_arguments(parser)
    parser.add_argument("user", help="@username or the id of the user")
    parser.add_argument("group", help="@groupname or the id of the group")
    args = parser.parse_args()

    result = await invite(args.user, args.group, **client_kwargs(args))
    emit(result, args.json_path, lambda data: print(f"Added {data['user']} to {data['group']}"))


if __name__ == "__main__":
    asyncio.run(main())
